### ISSUE TITLE
Using with jQueryMobile

### ISSUE THREAD

**Issue by mtamony** [filamentgroup/jqm-pagination#13]
Has anyone been able to get this to work with http://jquerymobile.com/test/docs/demos/swipe/swipe-page.html
I have a site where I am using this swipe functionality and it works well. When I add pagination to it things get a bit weird.

**Comment by SatguruSharanamMam** [comment]
Same case here :( Has anybody found a solution (if at all)? I am using jQuery mobile 1.4.5. Thanks in advance.
